### ISSUE TITLE
Validating Updates/Deletes

### ISSUE THREAD

**Issue by madushankaf** [tross-tyson/mdata_go#8]
Only the company that creates and bring in deletes/updates. Better to include that in the RFC.

**Comment by txross** [comment]
That functionality is discussed in https://github.com/tross-tyson/mdata_go/blob/client/docs/RFC.md#using-the-pike-processor-to-determine-ownership-and-agency

Without a processor like Pike verifying a node's organization, there is no easy way to determine if a node is a Sysco node editing Sysco product... Consider if Sysco node 1 posts the product and Sysco node 2 attempts to execute an update. I can code it so that only the original creating signing node can modify a product, but that limits the scalability of the processor. We would need a store that correlates public keys to organizations, which is what the Pike processor does.

**Comment by madushankaf** [comment]
Yeah, I meant in the Method descriptions but that is fine.
